Repository Polytoria/Docs, pull requests merged in 2023-12, with the labels that each got.

#29 Update InvokedServer.md
  docs/classes/NetworkEvent/Events/InvokedServer.md
Labels: documentation

#30 Update InvokedClient.md
  docs/classes/NetworkEvent/Events/InvokedClient.md
Labels: documentation

#31 Update SetParent.md
  docs/classes/Instance/Functions/SetParent.md
Labels: documentation, typographical

#32 change Instance.new to Instance.New
  docs/classes/BaseScript/index.md
  docs/classes/Climbable/index.md
  docs/classes/Environment/index.md
  docs/classes/Game/index.md
  docs/classes/Hidden/index.md
  docs/classes/Instance/index.md
  docs/classes/Lighting/index.md
  docs/classes/Player/index.md
  docs/classes/Players/index.md
  docs/classes/ScriptService/index.md
Labels: documentation, typographical

#33 grammar changes, better examples, updated invalid apis
  docs/classes/Tool/Functions/Play.md
  docs/static-classes/Http/Functions/Get.md
  docs/static-classes/json/Functions/parse.md
  docs/user-guide/basic/index.md
  docs/user-guide/basic/interface.md
Labels: documentation, typographical, code block
