Repository Polytoria/Docs, pull requests merged in 2024-01, with the labels that each got.

#38 Updated Deactivated.md
  docs/classes/Tool/Events/Deactivated.md
Labels: documentation, code block

#41 Fix Spotlight description
  docs/classes/Spotlight/index.md
Labels: documentation, typographical, doc error

#39 Update client specs
  docs/user-guide/basic/index.md
Labels: documentation, typographical
